# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.zhangbiao651.top:
  peer0.org1.zhangbiao651.top:
  peer1.org1.zhangbiao651.top:
  peer0.org1.zhangbiao651.top:
  peer1.org1.zhangbiao651.top:

networks:
  manager:
    name: fabric_manager
services:

  orderer.zhangbiao651.top:
    container_name: orderer.zhangbiao651.top
    image: hyperledger/fabric-orderer:2.2
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
#      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
#      - ORDERER_KAFKA_VERBOSE=true
#      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
#      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
#      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../data/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../orgs/ordererOrganizations/zhangbiao651.top/orderers/orderer.zhangbiao651.top/msp:/var/hyperledger/orderer/msp
        - ../orgs/ordererOrganizations/zhangbiao651.top/orderers/orderer.zhangbiao651.top/tls/:/var/hyperledger/orderer/tls
        - orderer.zhangbiao651.top:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - manager

  peer0.org1.zhangbiao651.top:
    container_name: peer0.org1.zhangbiao651.top
    image: hyperledger/fabric-peer:2.2
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fixtures_test
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org1.zhangbiao651.top
      - CORE_PEER_ADDRESS=peer0.org1.zhangbiao651.top:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.zhangbiao651.top:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.zhangbiao651.top:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.zhangbiao651.top:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
        #      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
    volumes:
        - /var/run/:/host/var/run/
        - ../orgs/peerOrganizations/org1.zhangbiao651.top/peers/peer0.org1.zhangbiao651.top/msp:/etc/hyperledger/fabric/msp
        - ../orgs/peerOrganizations/org1.zhangbiao651.top/peers/peer0.org1.zhangbiao651.top/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.zhangbiao651.top:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    depends_on:
      - orderer.zhangbiao651.top
      #- couchdb.org1.zhangbiao651.top
    networks:
      - manager

  peer1.org1.zhangbiao651.top:
    container_name: peer1.org1.zhangbiao651.top
    image: hyperledger/fabric-peer:2.2
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fixtures_test
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.org1.zhangbiao651.top
      - CORE_PEER_ADDRESS=peer1.org1.zhangbiao651.top:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.zhangbiao651.top:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.zhangbiao651.top:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.zhangbiao651.top:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
        #      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
    volumes:
        - /var/run/:/host/var/run/
        - ../orgs/peerOrganizations/org1.zhangbiao651.top/peers/peer1.org1.zhangbiao651.top/msp:/etc/hyperledger/fabric/msp
        - ../orgs/peerOrganizations/org1.zhangbiao651.top/peers/peer1.org1.zhangbiao651.top/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.zhangbiao651.top:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
    depends_on:
      - orderer.zhangbiao651.top
      #- couchdb.org1.zhangbiao651.top
    networks:
      - manager

  peer0.org2.zhangbiao651.top:
    container_name: peer0.org2.zhangbiao651.top
    image: hyperledger/fabric-peer:2.2
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fixtures_test
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org2.zhangbiao651.top
      - CORE_PEER_ADDRESS=peer0.org2.zhangbiao651.top:7151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7151
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.zhangbiao651.top:7152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7152
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.zhangbiao651.top:9151
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.zhangbiao651.top:7151
      - CORE_PEER_LOCALMSPID=Org2MSP
        #      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
    volumes:
        - /var/run/:/host/var/run/
        - ../orgs/peerOrganizations/org2.zhangbiao651.top/peers/peer0.org2.zhangbiao651.top/msp:/etc/hyperledger/fabric/msp
        - ../orgs/peerOrganizations/org2.zhangbiao651.top/peers/peer0.org2.zhangbiao651.top/tls:/etc/hyperledger/fabric/tls
          #        - peer0.org2.zhangbiao651.top:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7151:7151
    depends_on:
      - orderer.zhangbiao651.top
      #- couchdb.org2.zhangbiao651.top
    networks:
      - manager

  peer1.org2.zhangbiao651.top:
    container_name: peer1.org2.zhangbiao651.top
    image: hyperledger/fabric-peer:2.2
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fixtures_test
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.org2.zhangbiao651.top
      - CORE_PEER_ADDRESS=peer1.org2.zhangbiao651.top:9151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9151
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.zhangbiao651.top:9152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.zhangbiao651.top:9151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.zhangbiao651.top:7151
      - CORE_PEER_LOCALMSPID=Org2MSP
        #      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        #      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
    volumes:
        - /var/run/:/host/var/run/
        - ../orgs/peerOrganizations/org2.zhangbiao651.top/peers/peer1.org2.zhangbiao651.top/msp:/etc/hyperledger/fabric/msp
        - ../orgs/peerOrganizations/org2.zhangbiao651.top/peers/peer1.org2.zhangbiao651.top/tls:/etc/hyperledger/fabric/tls
          #- peer1.org2.zhangbiao651.top:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9151:9151
    depends_on:
      - orderer.zhangbiao651.top
      #- couchdb.org2.zhangbiao651.top
    networks:
      - manager
       

  ca.org1.zhangbiao651.top:
    image: hyperledger/fabric-ca:1.4.9
    container_name: ca.org1.zhangbiao651.top
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.zhangbiao651.top
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.zhangbiao651.top-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.zhangbiao651.top-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../orgs/peerOrganizations/org1.zhangbiao651.top/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - manager

  ca.org2.zhangbiao651.top:
    image: hyperledger/fabric-ca:1.4.9
    container_name: ca.org2.zhangbiao651.top
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.zhangbiao651.top
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.zhangbiao651.top-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.zhangbiao651.top-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - 7154:7154
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../orgs/peerOrganizations/org2.zhangbiao651.top/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - manager






        #  couchdb0:
        #    container_name: couchdb0
        #    image: hyperledger/fabric-couchdb:latest
        #    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
        #    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
        #    environment:
        #      - COUCHDB_USER=admin
        #      - COUCHDB_PASSWORD=123456
        #    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        #    # for example map it to utilize Fauxton User Interface in dev environments.
        #    ports:
        #      - "5984:5984"
        #    networks:
        #      - manager
        #
        #  couchdb1:
        #    container_name: couchdb1
        #    image: hyperledger/fabric-couchdb:latest
        #    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
        #    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
        #    environment:
        #      - COUCHDB_USER=admin
        #      - COUCHDB_PASSWORD=123456
        #    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        #    # for example map it to utilize Fauxton User Interface in dev environments.
        #    ports:
        #      - "7984:5984"
        #    networks:
        #      - manager
        #
        #  couchdb2:
        #    container_name: couchdb2
        #    image: hyperledger/fabric-couchdb:latest
        #    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
        #    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
        #    environment:
        #      - COUCHDB_USER=admin
        #      - COUCHDB_PASSWORD=123456
        #    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        #    # for example map it to utilize Fauxton User Interface in dev environments.
        #    ports:
        #      - "8984:5984"
        #    networks:
        #      - manager
        #
        #  couchdb3:
        #    container_name: couchdb3
        #    image: hyperledger/fabric-couchdb:latest
        #    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
        #    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
        #    environment:
        #      - COUCHDB_USER=admin
        #      - COUCHDB_PASSWORD=123456
        #    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        #    # for example map it to utilize Fauxton User Interface in dev environments.
        #    ports:
        #      - "9984:5984"
        #    networks:
        #      - manager
